package ie.ucd.cs.neilgrogan13204052.papers.dec11;

/**
* Created by Neil Grogan on 26/02/15
*/
public class Q2 {

    public static void main(String[] args) {
        // code here
    }

    /**
     * Suppose a method called methodTest() consists of a try block, followed by a catch block,
     * followed by a finally block. Assuming the JVM does not crash and the code does not execute a
     *System.exit() call, under what circumstances will the finally block not begin to execute?
     * (Choose all that apply)
     *
     * A. The try block throws an exception, and the catch block also throws an exception.
     * B. The try block throws an exception, and the catch block calls methodTest() in a way that
     *  causes another exception to be thrown.
     * C. Under the above conditions, the finally block will always execute.
     */
}
